hardware:
  publish_rate: 10

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

arm_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm1_1_joint
    - arm1_2_joint
    - arm2_1_joint
    - arm2_2_joint
    - arm3_joint
    - arm4_joint
    - gripper_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

head_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_camera_pan_joint
    - head_camera_tilt_joint
  constraints:
    stopped_velocity_tolerance: 0.5
    goal_time: 0.05
  allow_partial_joints_goal: true

dynamixel_port:
  port_name: "/dev/input/arm_pantilt"
  baud_rate: 3000000
  joints:
    - arm1_1_joint
    - arm1_2_joint
    - arm2_1_joint
    - arm2_2_joint
    - arm3_joint
    - arm4_joint
    - gripper_joint
    - head_camera_pan_joint
    - head_camera_tilt_joint
  arm1_1_joint: {id: 9, center: 2048, home: 1.57, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  arm1_2_joint: {id: 10, center: 2048, home: -1.57, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  arm2_1_joint: {id: 11, center: 2048, home: 1.57, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  arm2_2_joint: {id: 12, center: 2048, home: -1.57, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  arm3_joint: {id: 13, center: 2048, home: -1.57, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  arm4_joint: {id: 14, center: 2048, home: -1.57, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  gripper_joint: {id: 15, center: 2105, home: 0.0, mode: 5, vel: 0, acc: 0, pos_i_gain: 0, gear_ratio: 1, lim: 200 }
  head_camera_pan_joint: {id: 16, center: 2048, home: 0.0, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
  head_camera_tilt_joint: {id: 17, center: 2048, home: 0.0, mode: 3, vel: 0, acc: 0, pos_i_gain: 300, gear_ratio: 1 }
