dynamixel_port:
  port_name: "/dev/input/dx_upper"
  baud_rate: 3000000
  joints:
    - arm_shoulder_1_tilt_joint
    - arm_shoulder_2_tilt_joint
    - arm_elbow_upper_1_tilt_joint
    - arm_elbow_upper_2_tilt_joint
    - arm_elbow_lower_tilt_joint
    - arm_elbow_lower_pan_joint
    - arm_wrist_tilt_joint
    - hand_joint
  arm_shoulder_1_tilt_joint:    {id: 11, center: 2048, home:  1.57, mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain:  5, pos_p_gain: 1000, gear_ratio: 1 }
  arm_shoulder_2_tilt_joint:    {id: 12, center: 2048, home: -1.57, mode: 3, vel: 128, acc: 0, pos_d_gain: 1300, pos_i_gain:  5, pos_p_gain: 1000, gear_ratio: 1 }
  arm_elbow_upper_1_tilt_joint: {id: 13, center: 2048, home:  1.57, mode: 3, vel: 200, acc: 0, pos_d_gain: 2000, pos_i_gain: 10, pos_p_gain: 2000, gear_ratio: 1 }
  arm_elbow_upper_2_tilt_joint: {id: 14, center: 2048, home: -1.57, mode: 3, vel: 200, acc: 0, pos_d_gain: 2000, pos_i_gain: 10, pos_p_gain: 2000, gear_ratio: 1 }
  arm_elbow_lower_tilt_joint:   {id: 15, center: 2048, home: -1.57, mode: 3, vel: 200, acc: 0, pos_d_gain: 1500, pos_i_gain: 10, pos_p_gain: 1750, gear_ratio: 1 }
  arm_elbow_lower_pan_joint:    {id: 16, center: 2048, home:  0.00, mode: 3, vel: 200, acc: 0, pos_d_gain:    0, pos_i_gain:  0, pos_p_gain:  800, gear_ratio: 1 }
  arm_wrist_tilt_joint:         {id: 17, center: 2048, home: -1.57, mode: 3, vel: 200, acc: 0, pos_d_gain: 1250, pos_i_gain: 30, pos_p_gain: 1100, gear_ratio: 1 }
  hand_joint:                   {id: 18, center: 2048, home:  0.00, mode: 5, vel:   0, acc: 0, pos_d_gain:    0, pos_i_gain:  0, pos_p_gain:  800, gear_ratio: 1, lim: 150 }
